services:
  - type: web
    name: whatsapp-clone
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-clone-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true
    disk:
      name: whatsapp-uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: whatsapp-clone-db
    databaseName: whatsapp_clone
    user: postgres
    plan: free